### ISSUE TITLE
Fatal error with 7.18.4

### ISSUE THREAD

**Issue by Far2Sleepy** [springfall2008/batpred#1079]
'
2024-05-11 16:44:19.837661 WARNING pred_bat: ------------------------------------------------------------
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service appdaemon: stopping
[16:44:33] INFO: Service AppDaemon exited with code 0 (by signal 0)
s6-rc: info: service appdaemon successfully stopped
s6-rc: info: service init-appdaemon: stopping
s6-rc: info: service init-appdaemon successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------

 Add-on: appdaemon-predbat
 Predbat pre-install in AppDaemon
-----------------------------------------------------------
 Add-on version: 1.0.10
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.3  (amd64 / qemux86-64)
 Home Assistant Core: 2024.5.3
 Home Assistant Supervisor: 2024.05.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-appdaemon: starting
s6-rc: info: service init-appdaemon successfully started
s6-rc: info: service appdaemon: starting
s6-rc: info: service appdaemon successfully started
s6-rc: info: service legacy-services: starting
[16:44:37] INFO: Starting AppDaemon...
s6-rc: info: service legacy-services successfully started
2024-05-11 16:44:42.262775 WARNING pred_bat: ------------------------------------------------------------
2024-05-11 16:44:42.263046 WARNING pred_bat: Unexpected error running initialize() for pred_bat
2024-05-11 16:44:42.263202 WARNING pred_bat: ------------------------------------------------------------
2024-05-11 16:44:42.265431 WARNING pred_bat: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 162, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/apps/predbat.py", line 14367, in initialize
    raise e
  File "/config/apps/predbat.py", line 14363, in initialize
    self.load_user_config(quiet=False, register=True)
  File "/config/apps/predbat.py", line 14081, in load_user_config
    ha_value = self.load_previous_value_from_ha(entity)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/apps/predbat.py", line 14031, in load_previous_value_from_ha
    history = self.get_history_wrapper(entity_id=entity)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/apps/predbat.py", line 5050, in get_history_wrapper
    history = self.ha_interface.get_history(entity_id, days=days, now=self.now)
                                                                      ^^^^^^^^
AttributeError: 'PredBat' object has no attribute 'now'

2024-05-11 16:44:42.266529 WARNING pred_bat: ------------------------------------------------------------
'

**Comment by Far2Sleepy** [comment]
Thank you. v7.18.6 did the trick
