### ISSUE TITLE
Predbat Status - "ERROR: Exception raised 'PredBat' object has no attribute 'now;"

### ISSUE THREAD

**Issue by TheSargey** [springfall2008/batpred#1080]
**Describe the bug**
Tried to upgrade from an older version (7.17.4) to the latest 7.18.4

**Expected behavior**
Expected it to upgrade

**Predbat version**

7.17.4

**Environment details**

- Inverter and battery setup - GivEnergy
- Standard HAOS installer or Docker - Appdaemon-Predbat install

**Log file**
-----------------------------------------------------------
 Add-on: appdaemon-predbat
 Predbat pre-install in AppDaemon
-----------------------------------------------------------
 Add-on version: 1.0.10
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.0  (amd64 / qemux86-64)
 Home Assistant Core: 2024.3.0
 Home Assistant Supervisor: 2024.05.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-appdaemon: starting
s6-rc: info: service init-appdaemon successfully started
s6-rc: info: service appdaemon: starting
s6-rc: info: service appdaemon successfully started
s6-rc: info: service legacy-services: starting
[17:42:28] INFO: Starting AppDaemon...
s6-rc: info: service legacy-services successfully started
2024-05-11 17:42:37.311479 WARNING pred_bat: ------------------------------------------------------------
2024-05-11 17:42:37.312113 WARNING pred_bat: Unexpected error running initialize() for pred_bat
2024-05-11 17:42:37.312307 WARNING pred_bat: ------------------------------------------------------------
2024-05-11 17:42:37.315114 WARNING pred_bat: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 162, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/apps/predbat.py", line 14367, in initialize
    raise e
  File "/config/apps/predbat.py", line 14363, in initialize
    self.load_user_config(quiet=False, register=True)
  File "/config/apps/predbat.py", line 14081, in load_user_config
    ha_value = self.load_previous_value_from_ha(entity)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/apps/predbat.py", line 14031, in load_previous_value_from_ha
    history = self.get_history_wrapper(entity_id=entity)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/apps/predbat.py", line 5050, in get_history_wrapper
    history = self.ha_interface.get_history(entity_id, days=days, now=self.now)
                                                                      ^^^^^^^^
AttributeError: 'PredBat' object has no attribute 'now'

2024-05-11 17:42:37.315382 WARNING pred_bat: ------------------------------------------------------------

It looks like AppDaemon has stopped working, Predbat seems ok in that all of the graphs and everything work, the controls and so forth are populated however I don't think it's actually running. I can't downgrade/upgrade versions and when I try and restart AppDaemon I get the same issue above.  I can't set it to auto-update.

What's the best way to get back to a working PredBat?  Just uninstall everything and start again?  Just adverse to that as I'll lose all the amendments I made to the plans and so forth (I think I will anyway) or is that the only option?

Thanks as always for the advice.

Cheers,

Sarge

**Comment by TheSargey** [comment]
Just to add, I've updated HomeAssistant and now I've lost PredBat so I'll probably just reinstall and see where I get to.

**Comment by TheSargey** [comment]
Sadly, uninstall and reinstall of appdaemon-predbat gets the same result

-----------------------------------------------------------

 Add-on: appdaemon-predbat
 Predbat pre-install in AppDaemon
-----------------------------------------------------------
 Add-on version: 1.0.10
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.3  (amd64 / qemux86-64)
 Home Assistant Core: 2024.5.3
 Home Assistant Supervisor: 2024.05.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-appdaemon: starting
s6-rc: info: service init-appdaemon successfully started
s6-rc: info: service appdaemon: starting
s6-rc: info: service appdaemon successfully started
s6-rc: info: service legacy-services: starting
[18:19:00] INFO: Starting AppDaemon...
s6-rc: info: service legacy-services successfully started
2024-05-11 18:19:08.908008 WARNING pred_bat: ------------------------------------------------------------
2024-05-11 18:19:08.908516 WARNING pred_bat: Unexpected error running initialize() for pred_bat
2024-05-11 18:19:08.908957 WARNING pred_bat: ------------------------------------------------------------
2024-05-11 18:19:08.913668 WARNING pred_bat: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 162, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/apps/predbat.py", line 14367, in initialize
    raise e
  File "/config/apps/predbat.py", line 14363, in initialize
    self.load_user_config(quiet=False, register=True)
  File "/config/apps/predbat.py", line 14081, in load_user_config
    ha_value = self.load_previous_value_from_ha(entity)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/apps/predbat.py", line 14031, in load_previous_value_from_ha
    history = self.get_history_wrapper(entity_id=entity)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/apps/predbat.py", line 5050, in get_history_wrapper
    history = self.ha_interface.get_history(entity_id, days=days, now=self.now)
                                                                      ^^^^^^^^
AttributeError: 'PredBat' object has no attribute 'now'

2024-05-11 18:19:08.915083 WARNING pred_bat: ------------------------------------------------------------


Any help appreciated.

Cheers,

Sarge

**Comment by TheSargey** [comment]
Just to update, uninstalled Predbat (had to rename the old AppDaemon-predbat folder as a reinstall without this would result in the same error) and installed "fresh" and I'm back up and running on 7.18.2 - looks stable on this so far so not going to update for a bit until things settle!

Cheers,

Sarge
