### ISSUE TITLE
Exception raised when updating to v7.19.2

### ISSUE THREAD

**Issue by SwiftRR** [springfall2008/batpred#1115]
**Describe the bug**
I updated to v7.19.2 and got an instant exception error:
Changed to ERROR: Exception raised Pool not running
15:06:28 - 11 minutes ago - Supervisor

My appdaemon-predbat add on log was a mess!
I then reverted to v7.19.1, restarted the appdaemon-predbat add on and recovered predbat.
I do not have automatic update enabled.
BUT predbat states that I am on v7.19.2 !
I have noticed in the meantime that v7.19.3 has appeared. I will leave it to settle for a while!

**Expected behavior**

**Predbat version**
v7.19.2

**Environment details**
- Inverter and battery setup: GE AC coupled inverter with two 8.2 kWh batteries
- HAOS on raspberry pi4

**Log file**
predbat.log. attached with appdaemon-predbat add on shown below
[predbat-2.log](https://github.com/springfall2008/batpred/files/15365597/predbat-2.log)

2024-05-18 15:06:28.201605 WARNING pred_bat: ------------------------------------------------------------
2024-05-18 15:06:28.219935 WARNING pred_bat: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/threading.py", line 1022, in worker
    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/usr/lib/python3.11/site-packages/appdaemon/adbase.py", line 35, in f_app_lock
    return f(*args, **kw)
           ^^^^^^^^^^^^^^
  File "/config/apps/predbat.py", line 14802, in run_time_loop
    raise e
  File "/config/apps/predbat.py", line 14798, in run_time_loop
    self.update_pred(scheduled=True)
  File "/usr/lib/python3.11/site-packages/appdaemon/adbase.py", line 35, in f_app_lock
    return f(*args, **kw)
           ^^^^^^^^^^^^^^
  File "/config/apps/predbat.py", line 13707, in update_pred
    self.calculate_plan(recompute=True)
  File "/config/apps/predbat.py", line 11970, in calculate_plan
    self.optimise_all_windows(metric, metric_keep)
  File "/config/apps/predbat.py", line 10923, in optimise_all_windows
    best_soc, best_metric, best_cost, soc_min, soc_min_minute, best_keep, best_cycle, best_carbon = self.optimise_charge_limit(
                                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/apps/predbat.py", line 9801, in optimise_charge_limit
    hans.append(self.launch_run_prediction_charge(loop_soc, window_n, charge_limit, charge_window, discharge_window, discharge_limits, False, all_n, end_record))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/apps/predbat.py", line 9540, in launch_run_prediction_charge
    han = self.pool.apply_async(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 458, in apply_async
    self._check_running()
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 353, in _check_running
    raise ValueError("Pool not running")
ValueError: Pool not running

Update complete
2024-05-18 15:06:28.223359 WARNING pred_bat: ------------------------------------------------------------
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service appdaemon: stopping
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: appdaemon-predbat
 Predbat pre-install in AppDaemon
-----------------------------------------------------------
 Add-on version: 1.0.10
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.3.3
 Home Assistant Supervisor: 2024.05.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-appdaemon: starting
s6-rc: info: service init-appdaemon successfully started
s6-rc: info: service appdaemon: starting
s6-rc: info: service appdaemon successfully started
s6-rc: info: service legacy-services: starting
[15:07:45] INFO: Starting AppDaemon...
s6-rc: info: service legacy-services successfully started

**Comment by SwiftRR** [comment]
This issue overlaps with #1107 and my issue did sort itself out anyway.
Closed
