### ISSUE TITLE
Error when updating to 7.20.0

### ISSUE THREAD

**Issue by PianSom** [springfall2008/batpred#1141]
Using HA Container, with AppDaemon in its own container. Updated from HA

In logfile.txt:
```
2024-05-26 15:11:12.948007 INFO pred_bat: Error: Failure to fetch history for sensor.givtcp_ch2316g275_battery_power
2024-05-26 15:11:12.950599 INFO pred_bat: ERROR: Exception raised 
2024-05-26 15:11:12.975923 WARNING AppDaemon: Logged an error to /conf/logs/errorfile.txt
```

In errorfile.txt:
<details><summary>errorfile.txt</summary>
<p>

2024-05-26 15:10:17.744650 WARNING pred_bat: ------------------------------------------------------------
2024-05-26 15:10:17.746331 WARNING pred_bat: Unexpected error in worker for App pred_bat:
2024-05-26 15:10:17.747524 WARNING pred_bat: Worker Ags: {'id': 'e7d934db0f08442c8f7c80a2023a3e21', 'name': 'pred_bat', 'objectid': 'b6eb66b30a694bbeadb61a4d369f9dcd', 'type': 'scheduler', 'function': <bound method PredBat.run_time_loop of <predbat.PredBat object at 0x7f3e85a24a00>>, 'pin_app': True, 'pin_thread': 3, 'kwargs': {'interval': 300, 'random_start': 0, 'random_end': 0, '__thread_id': 'thread-3'}}
2024-05-26 15:10:17.747877 WARNING pred_bat: ------------------------------------------------------------
2024-05-26 15:10:17.754211 WARNING pred_bat: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/appdaemon/threading.py", line 1022, in worker
    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/usr/local/lib/python3.10/site-packages/appdaemon/adbase.py", line 35, in f_app_lock
    return f(*args, **kw)
  File "/conf/apps/predbat/predbat.py", line 15066, in run_time_loop
    raise e
  File "/conf/apps/predbat/predbat.py", line 15062, in run_time_loop
    self.update_pred(scheduled=True)
  File "/usr/local/lib/python3.10/site-packages/appdaemon/adbase.py", line 35, in f_app_lock
    return f(*args, **kw)
  File "/conf/apps/predbat/predbat.py", line 13951, in update_pred
    self.calculate_plan(recompute=True)
  File "/conf/apps/predbat/predbat.py", line 12220, in calculate_plan
    self.optimise_all_windows(metric, metric_keep)
  File "/conf/apps/predbat/predbat.py", line 11164, in optimise_all_windows
    best_soc, best_metric, best_cost, soc_min, soc_min_minute, best_keep, best_cycle, best_carbon = self.optimise_charge_limit(
  File "/conf/apps/predbat/predbat.py", line 10035, in optimise_charge_limit
    hans.append(self.launch_run_prediction_charge(loop_soc, window_n, charge_limit, charge_window, discharge_window, discharge_limits, False, all_n, end_record))
  File "/conf/apps/predbat/predbat.py", line 9782, in launch_run_prediction_charge
    han = self.pool.apply_async(
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 458, in apply_async
    self._check_running()
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 353, in _check_running
    raise ValueError("Pool not running")
ValueError: Pool not running

2024-05-26 15:10:17.756146 WARNING pred_bat: ------------------------------------------------------------
2024-05-26 15:10:26.072916 WARNING pred_bat: ------------------------------------------------------------
2024-05-26 15:10:26.073306 WARNING pred_bat: Unexpected error in worker for App pred_bat:
2024-05-26 15:10:26.073513 WARNING pred_bat: Worker Ags: {'id': 'a4739224312f4f318bc89b8b2766a54a', 'name': 'pred_bat', 'objectid': 'b6eb66b30a694bbeadb61a4d369f9dcd', 'type': 'scheduler', 'function': <bound method PredBat.update_time_loop of <predbat.PredBat object at 0x7f3e85a24a00>>, 'pin_app': True, 'pin_thread': 3, 'kwargs': {'interval': 15, 'random_start': 0, 'random_end': 0, '__thread_id': 'thread-3'}}
2024-05-26 15:10:26.074923 WARNING pred_bat: ------------------------------------------------------------
2024-05-26 15:10:26.075540 WARNING pred_bat: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/appdaemon/threading.py", line 1022, in worker
    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/usr/local/lib/python3.10/site-packages/appdaemon/adbase.py", line 35, in f_app_lock
    return f(*args, **kw)
  File "/conf/apps/predbat/predbat.py", line 15044, in update_time_loop
    self.log("Best SOC array {}".format(soc_best))
  File "/conf/apps/predbat/predbat.py", line 15039, in update_time_loop
    if SIMULATE and SIMULATE_LENGTH:
  File "/usr/local/lib/python3.10/site-packages/appdaemon/adbase.py", line 35, in f_app_lock
    return f(*args, **kw)
  File "/conf/apps/predbat/predbat.py", line 13917, in update_pred
    now_utc = self.now_utc_real + timedelta(minutes=skew)
  File "/conf/apps/predbat/predbat.py", line 13445, in fetch_inverter_data
    self.publish_rates(self.rate_gas, False, gas=True)
  File "/conf/apps/predbat/predbat.py", line 2352, in __init__
    old_pause_mode = self.base.get_state_wrapper(entity_mode)
AttributeError: 'PredBat' object has no attribute 'get_state_wrapper'

2024-05-26 15:10:26.075806 WARNING pred_bat: ------------------------------------------------------------
2024-05-26 15:11:12.962906 WARNING pred_bat: ------------------------------------------------------------
2024-05-26 15:11:12.968955 WARNING pred_bat: Unexpected error in worker for App pred_bat:
2024-05-26 15:11:12.972479 WARNING pred_bat: Worker Ags: {'id': '2ab9a78b7ec04f8399f28c1dc505de62', 'name': 'pred_bat', 'objectid': 'a8fbef7dfd0c45ef9fd7850173d52638', 'type': 'scheduler', 'function': <bound method PredBat.update_time_loop of <predbat.PredBat object at 0x7f3e7ef20a90>>, 'pin_app': True, 'pin_thread': 3, 'kwargs': {'interval': 15, 'random_start': 0, 'random_end': 0, '__thread_id': 'thread-3'}}
2024-05-26 15:11:12.973285 WARNING pred_bat: ------------------------------------------------------------
2024-05-26 15:11:12.974490 WARNING pred_bat: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/appdaemon/threading.py", line 1022, in worker
    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/conf/apps/predbat/predbat.py", line 15108, in update_time_loop
    raise e
  File "/conf/apps/predbat/predbat.py", line 15103, in update_time_loop
    self.update_pred(scheduled=False)
  File "/conf/apps/predbat/predbat.py", line 13952, in update_pred
    self.fetch_inverter_data()
  File "/conf/apps/predbat/predbat.py", line 13481, in fetch_inverter_data
    curve = inverter.find_charge_curve(discharge=False)
  File "/conf/apps/predbat/predbat.py", line 2590, in find_charge_curve
    battery_power_data = self.base.get_history_wrapper(entity_id=battery_power_sensor, days=self.base.max_days_previous)
  File "/conf/apps/predbat/predbat.py", line 5094, in get_history_wrapper
    raise ValueError
ValueError

2024-05-26 15:11:12.975171 WARNING pred_bat: ------------------------------------------------------------

</p>
</details> 

Error cleared after AppDaemon restart.

**Comment by springfall2008** [comment]
Looks like the change of code structure caused a mismatch between the active code and the file on disk, should hopefully not happen again
