### ISSUE TITLE
Alpha ESS Support

### ISSUE THREAD

**Issue by dhi20** [springfall2008/batpred#1189]
Has anyone had any luck integrating the Alpha ESS?

I've been working on the basis of control via service calls within Home Assistant but I'm getting stuck on start charge which seems to be failing on 'adjust_discharge_rate'

The stop charge service is working.

```
Traceback (most recent call last):
  File "/config/hass.py", line 162, in timer_tick
    item["callback"](None)
  File "/config/predbat.py", line 15423, in update_time_loop
    raise e
  File "/config/predbat.py", line 15417, in update_time_loop
    self.update_pred(scheduled=False)
  File "/config/predbat.py", line 14310, in update_pred
    status, status_extra = self.execute_plan()
  File "/config/predbat.py", line 12897, in execute_plan
    inverter.adjust_discharge_rate(0)
  File "/config/predbat.py", line 3320, in adjust_discharge_rate
    self.write_and_poll_value(
  File "/config/predbat.py", line 3428, in write_and_poll_value
    domain, entity_name = entity_id.split(".")
AttributeError: 'int' object has no attribute 'split'
```

**Comment by dc42** [comment]
@dhi20 did you get anywhere with this? I want to integrate my Alpha-ESS SMILE5 inverter with HA too. I already have reporting and manual control of it by building https://github.com/dxoverdy/Alpha2MQTT and using the instructions at https://github.com/dxoverdy/Integrating-Alpha2MQTT-with-Home-Assistant.
