### ISSUE TITLE
Error with v8.1.1 - TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'

### ISSUE THREAD

**Issue by TheSargey** [springfall2008/batpred#1249]
Howdy folks,

Just a quick one, was hoping I could get some brief advice on the best route to upgrade from v7.19.7 to v8.1.1 - I note that I should upgrade to 7.22.5 first before going further however I see there's been some adjustment in the predbat-appdaemon configuration (which I'm currently using on my HAOS setup).

Is there a new FAQ around this or a closed topic as I've not been able to find it directly.

Thanks for help as always,

Sarge

**Comment by gcoan** [comment]
Yes as per the title of the upgrades,  you must upgrade to 7.22.5 FIRST, let Predbat run and complete a full normal run,  then you can upgrade to any v8.x.x version.

You can use the select.predbat_update control or HACS if you are using the original AppDaemon installation method.

Don't turn on automatic updates (until you are on v8) as you need to upgrade to the interim version first

Probably should be put somewhere in the FAQ's or installation instructions, yes

**Comment by TheSargey** [comment]
Hi Geoff,

That's great, thanks. I normally just update through the control so I'll go
with that.

Thanks again and all the best,

Sarge

**Comment by TheSargey** [comment]
Sorry @gcoan - in my HAOS I have an update for appdaemon-predbat pending as well (to v1.0.11) should I update this as well before moving to V8?

Cheers,

Sarge

**Comment by gcoan** [comment]
I'd suggest upgrading the AppDaemon predbat first as that contains a bundled version of predbat and may well take it to v8 in one go

**Comment by TheSargey** [comment]
Thanks Geoff, upgraded to v8 no issues, then when to latest and now my status is "Changed to Error: Exception raised unsupported operand type(s) for +=: 'float' and 'NoneType'"  -  drat and blast!  Just having a look through now to see if there's something I've missed along the way.

**Comment by TheSargey** [comment]
predbat.log has this error:

2024-06-24 23:30:00.052787 INFO pred_bat: --------------- PredBat - update at 2024-06-24 23:30:00+01:00 with clock skew 0 minutes, minutes now 1410
2024-06-24 23:30:00.055394 INFO pred_bat: Saved current settings to /config/predbat_config.json
2024-06-24 23:30:00.057672 INFO pred_bat: Using cached GITHub data for https://api.github.com/repos/springfall2008/batpred/releases age 7.8 minutes
2024-06-24 23:30:00.059220 INFO pred_bat: Predbat /config/apps/predbat.py version v8.1.1 currently running, latest version is v8.1.1 latest beta v8.1.1
2024-06-24 23:30:00.060853 INFO pred_bat: Autoupdate: Currently up to date
2024-06-24 23:30:00.530494 INFO pred_bat: Configuration: forecast_hours 48 num_cars 0 debug enable is False calculate_plan_every 10
2024-06-24 23:30:00.539938 INFO pred_bat: Predbat mode is set to Control charge & discharge
2024-06-24 23:30:04.831088 INFO pred_bat: Found 31680 load_today datapoints going back 10 days
2024-06-24 23:30:07.896572 INFO pred_bat: Car charging hold True threshold 6.0
2024-06-24 23:30:07.916431 INFO pred_bat: Current data so far today: load 30.7 kWh import 16.8 kWh export 0.0 kWh pv 15.4 kWh
2024-06-24 23:30:07.918455 INFO pred_bat: Fetching futurerate data from None
2024-06-24 23:30:07.997518 INFO pred_bat: Standing charge is set to 42.0105 p
2024-06-24 23:30:10.820086 INFO pred_bat: Rate min forward looking: now 13.31 at end of forecast 13.31
2024-06-24 23:30:10.831789 INFO pred_bat: Import rates min 13.31 max 37.0 average 19.83
2024-06-24 23:30:10.904721 INFO pred_bat: Export rates min 0 max 0 average 0.0
2024-06-24 23:30:10.907822 INFO pred_bat: Rate thresholds (for charge/discharge) are import 36.5p (0.0) export 13.31p (0.0)
2024-06-24 23:30:10.912999 INFO pred_bat: High export rate found rates in range 99 to -99
2024-06-24 23:30:10.926309 INFO pred_bat: Low Import rate found rates in range 13.31 to 34.22
2024-06-24 23:30:11.320375 INFO pred_bat: Todays energy import 16.8 kWh export 0.0 kWh cost 328.34 p import 328.34 p export 0.0 p carbon 0.0 kg
2024-06-24 23:30:11.343595 INFO pred_bat: Using solcast from inside HA
2024-06-24 23:30:11.350799 INFO pred_bat: PV Data for pv_forecast_today total 16.34 kWh
2024-06-24 23:30:11.385042 INFO pred_bat: PV Data for pv_forecast_tomorrow total 18.04 kWh
2024-06-24 23:30:11.419766 INFO pred_bat: PV Data for pv_forecast_d3 total 15.97 kWh
2024-06-24 23:30:11.450708 INFO pred_bat: PV Data for pv_forecast_d4 total 19.1 kWh
2024-06-24 23:30:11.510195 INFO pred_bat: PV Forecast for today is 16.34 (12.46 10% 20.8 90%) kWh and left today is 0.0 (0.0 10% 0.0 90%) kWh
2024-06-24 23:30:11.625202 INFO pred_bat: PV Forecast for day tomorrow is 18.04 (13.61 10% 21.81 90%) kWh
2024-06-24 23:30:11.862279 INFO pred_bat: PV Forecast for day d2 is 15.97 (10.01 10% 22.55 90%) kWh
2024-06-24 23:30:12.027379 INFO pred_bat: PV Forecast for day d3 is 19.1 (5.99 10% 24.88 90%) kWh
2024-06-24 23:30:12.408218 INFO pred_bat: Historical data totals for days [7, 14, 21] are [29.2, 29.46, 29.46] - min 29.2
2024-06-24 23:30:12.423656 INFO pred_bat: Model filter enabled - Discarding day 7 as it is the lowest of the 3 datapoints
2024-06-24 23:30:12.429310 INFO pred_bat: Historical days now [14, 21] weight [1, 1]
2024-06-24 23:30:12.531369 INFO pred_bat: Today's load divergence 111.64 % in-day adjustment 111.05 % damping 0.95x, Predicted so far 21.62 kWh with 0.0 kWh car excluded and 2.14 kWh import ignored and 0 forecast extra, Actual so far 24.53 kWh with 1.05 kWh car excluded and 5.09 kWh import ignored
2024-06-24 23:30:12.875399 INFO pred_bat: Inverter 0: Type GE GivEnergy
2024-06-24 23:30:12.877494 INFO pred_bat: Inverter 0 using Rest API http://homeassistant.local:6345
2024-06-24 23:30:13.955118 INFO pred_bat: Inverter 0 does not have timed pause support enabled
2024-06-24 23:30:13.961146 INFO pred_bat: Invertor time 2024-06-24 23:29:50+01:00 AppDaemon time 2024-06-24 23:30:13.955538+01:00 difference -0.4 minutes
2024-06-24 23:30:13.967566 INFO pred_bat: Reserve min: 4.0% Battery_min:4.0%
2024-06-24 23:30:13.972487 INFO pred_bat: Inverter 0 with soc_max 10.44 kWh nominal_capacity 10.44 kWh battery rate raw 2600 w charge rate 2.6 kW discharge rate 2.6 kW battery_rate_min 0.0 w ac limit 3.6 kW export limit 3.6 kW reserve 4.0 % current_reserve 4.0 %
2024-06-24 23:30:15.580882 INFO pred_bat: Inverter 0 SOC: 0.52 kW 5 % Current charge rate 2600.0 w Current discharge rate 2600.0 w Current power 1552.0 w Current voltage 52.0
2024-06-24 23:30:15.597365 INFO pred_bat: Inverter 0 scheduled charge enable is False
2024-06-24 23:30:15.601604 INFO pred_bat: Inverter 0 charge windows currently []
2024-06-24 23:30:15.606859 INFO pred_bat: Inverter 0 Charge settings: timed charged is disabled, power 2.6 kW
2024-06-24 23:30:15.609867 INFO pred_bat: Inverter 0 Wrote scheduled_discharge_enable to False successfully and got off
2024-06-24 23:30:15.618471 INFO pred_bat: Inverter 0 sensor.predbat_GE_0_scheduled_discharge_enable set to False
2024-06-24 23:30:15.622309 INFO pred_bat: Inverter 0 scheduled discharge enable is False
2024-06-24 23:30:15.625781 INFO pred_bat: Inverter 0 discharge windows currently [{'start': 0, 'end': 0, 'average': 0}, {'start': 1440, 'end': 1440, 'average': 0}]
2024-06-24 23:30:15.628683 INFO pred_bat: Found 1 inverters totals: min reserve 0.42 current reserve 0.42 soc_max 10.44 soc 0.52 charge rate 2.6 kW discharge rate 2.6 kW battery_rate_min 0.0 w ac limit 3.6 export limit 3.6 kW loss charge 3 % loss discharge 3 % inverter loss 4 %
2024-06-24 23:30:16.010917 INFO pred_bat: Base charge    window [  ]
2024-06-24 23:30:16.020158 INFO pred_bat: Base discharge window [ 24-06 00:00:00 - 24-06 00:00:00 @ 0p 100.0%, 25-06 00:00:00 - 25-06 00:00:00 @ 0p 100.0% ]
2024-06-24 23:30:16.021882 INFO pred_bat: Will recompute the plan as it is invalid
2024-06-24 23:30:16.027860 INFO pred_bat: Best charge    window [ 24-06 23:30:00 - 25-06 00:00:00 @ 16.54p 0.0%, 25-06 00:00:00 - 25-06 00:30:00 @ 14.89p 0.0%, 25-06 00:30:00 - 25-06 01:00:00 @ 14.55p 0.0%, 25-06 01:00:00 - 25-06 01:30:00 @ 14.89p 0.0%, 25-06 01:30:00 - 25-06 02:00:00 @ 15.26p 0.0%, 25-06 02:00:00 - 25-06 02:30:00 @ 14.89p 0.0%, 25-06 02:30:00 - 25-06 03:00:00 @ 14.77p 0.0%, 25-06 03:00:00 - 25-06 03:30:00 @ 13.89p 0.0%, 25-06 03:30:00 - 25-06 04:00:00 @ 13.31p 0.0%, 25-06 04:00:00 - 25-06 04:30:00 @ 17.26p 0.0%, 25-06 04:30:00 - 25-06 05:00:00 @ 15.98p 0.0%, 25-06 05:00:00 - 25-06 05:30:00 @ 18.75p 0.0%, 25-06 05:30:00 - 25-06 06:00:00 @ 17.64p 0.0%, 25-06 06:00:00 - 25-06 06:30:00 @ 20.95p 0.0%, 25-06 06:30:00 - 25-06 07:00:00 @ 23.17p 0.0%, 25-06 07:00:00 - 25-06 07:30:00 @ 19.6p 0.0%, 25-06 07:30:00 - 25-06 08:00:00 @ 23.81p 0.0%, 25-06 08:00:00 - 25-06 08:30:00 @ 20.29p 0.0%, 25-06 08:30:00 - 25-06 09:00:00 @ 19.12p 0.0%, 25-06 09:00:00 - 25-06 09:30:00 @ 19.32p 0.0%, 25-06 09:30:00 - 25-06 10:00:00 @ 17.64p 0.0%, 25-06 10:00:00 - 25-06 10:30:00 @ 15.94p 0.0%, 25-06 10:30:00 - 25-06 11:00:00 @ 15.66p 0.0%, 25-06 11:00:00 - 25-06 11:30:00 @ 16.21p 0.0%, 25-06 11:30:00 - 25-06 12:00:00 @ 16.16p 0.0%, 25-06 12:00:00 - 25-06 12:30:00 @ 16.42p 0.0%, 25-06 12:30:00 - 25-06 13:00:00 @ 16.23p 0.0%, 25-06 13:00:00 - 25-06 13:30:00 @ 16.05p 0.0%, 25-06 13:30:00 - 25-06 14:00:00 @ 15.94p 0.0%, 25-06 14:00:00 - 25-06 14:30:00 @ 15.86p 0.0%, 25-06 14:30:00 - 25-06 15:00:00 @ 15.9p 0.0%, 25-06 15:00:00 - 25-06 15:30:00 @ 15.94p 0.0%, 25-06 15:30:00 - 25-06 16:00:00 @ 16.67p 0.0%, 25-06 16:00:00 - 25-06 16:30:00 @ 30.57p 0.0%, 25-06 16:30:00 - 25-06 17:00:00 @ 32.79p 0.0%, 25-06 17:00:00 - 25-06 17:30:00 @ 32.39p 0.0%, 25-06 17:30:00 - 25-06 18:00:00 @ 34.22p 0.0%, 25-06 19:00:00 - 25-06 19:30:00 @ 25.49p 0.0%, 25-06 19:30:00 - 25-06 20:00:00 @ 24.83p 0.0%, 25-06 20:00:00 - 25-06 20:30:00 @ 23.29p 0.0%, 25-06 20:30:00 - 25-06 21:00:00 @ 22.29p 0.0%, 25-06 21:00:00 - 25-06 21:30:00 @ 20.88p 0.0%, 25-06 21:30:00 - 25-06 22:00:00 @ 19.85p 0.0%, 25-06 22:00:00 - 25-06 22:30:00 @ 18.74p 0.0%, 25-06 22:30:00 - 25-06 23:00:00 @ 16.52p 0.0%, 25-06 23:00:00 - 25-06 23:30:00 @ 16.89p 0.0%, 25-06 23:30:00 - 26-06 00:00:00 @ 16.54p 0.0%, 26-06 00:00:00 - 26-06 00:30:00 @ 14.89p 0.0%, 26-06 00:30:00 - 26-06 01:00:00 @ 14.55p 0.0%, 26-06 01:00:00 - 26-06 01:30:00 @ 14.89p 0.0%, 26-06 01:30:00 - 26-06 02:00:00 @ 15.26p 0.0%, 26-06 02:00:00 - 26-06 02:30:00 @ 14.89p 0.0%, 26-06 02:30:00 - 26-06 03:00:00 @ 14.77p 0.0%, 26-06 03:00:00 - 26-06 03:30:00 @ 13.89p 0.0%, 26-06 03:30:00 - 26-06 04:00:00 @ 13.31p 0.0%, 26-06 04:00:00 - 26-06 04:30:00 @ 17.26p 0.0%, 26-06 04:30:00 - 26-06 05:00:00 @ 15.98p 0.0%, 26-06 05:00:00 - 26-06 05:30:00 @ 18.75p 0.0%, 26-06 05:30:00 - 26-06 06:00:00 @ 17.64p 0.0%, 26-06 06:00:00 - 26-06 06:30:00 @ 20.95p 0.0%, 26-06 06:30:00 - 26-06 07:00:00 @ 23.17p 0.0%, 26-06 07:00:00 - 26-06 07:30:00 @ 19.6p 0.0%, 26-06 07:30:00 - 26-06 08:00:00 @ 23.81p 0.0%, 26-06 08:00:00 - 26-06 08:30:00 @ 20.29p 0.0%, 26-06 08:30:00 - 26-06 09:00:00 @ 19.12p 0.0%, 26-06 09:00:00 - 26-06 09:30:00 @ 19.32p 0.0%, 26-06 09:30:00 - 26-06 10:00:00 @ 17.64p 0.0%, 26-06 10:00:00 - 26-06 10:30:00 @ 15.94p 0.0%, 26-06 10:30:00 - 26-06 11:00:00 @ 15.66p 0.0%, 26-06 11:00:00 - 26-06 11:30:00 @ 16.21p 0.0%, 26-06 11:30:00 - 26-06 12:00:00 @ 16.16p 0.0%, 26-06 12:00:00 - 26-06 12:30:00 @ 16.42p 0.0%, 26-06 12:30:00 - 26-06 13:00:00 @ 16.23p 0.0%, 26-06 13:00:00 - 26-06 13:30:00 @ 16.05p 0.0%, 26-06 13:30:00 - 26-06 14:00:00 @ 15.94p 0.0%, 26-06 14:00:00 - 26-06 14:30:00 @ 15.86p 0.0%, 26-06 14:30:00 - 26-06 15:00:00 @ 15.9p 0.0%, 26-06 15:00:00 - 26-06 15:30:00 @ 15.94p 0.0%, 26-06 15:30:00 - 26-06 16:00:00 @ 16.67p 0.0%, 26-06 16:00:00 - 26-06 16:30:00 @ 30.57p 0.0%, 26-06 16:30:00 - 26-06 17:00:00 @ 32.79p 0.0%, 26-06 17:00:00 - 26-06 17:30:00 @ 32.39p 0.0%, 26-06 17:30:00 - 26-06 18:00:00 @ 34.22p 0.0%, 26-06 19:00:00 - 26-06 19:30:00 @ 25.49p 0.0%, 26-06 19:30:00 - 26-06 20:00:00 @ 24.83p 0.0%, 26-06 20:00:00 - 26-06 20:30:00 @ 23.29p 0.0%, 26-06 20:30:00 - 26-06 21:00:00 @ 22.29p 0.0%, 26-06 21:00:00 - 26-06 21:30:00 @ 20.88p 0.0%, 26-06 21:30:00 - 26-06 22:00:00 @ 19.85p 0.0%, 26-06 22:00:00 - 26-06 22:30:00 @ 18.74p 0.0%, 26-06 22:30:00 - 26-06 23:00:00 @ 16.52p 0.0%, 26-06 23:00:00 - 26-06 23:30:00 @ 16.89p 0.0% ]
2024-06-24 23:30:16.029521 INFO pred_bat: Best discharge window [  ]
2024-06-24 23:30:16.033266 INFO pred_bat: PV Forecast 34.0 kWh and 10% Forecast 23.6 kWh pv cloud factor 0.2
2024-06-24 23:30:16.043013 INFO pred_bat: Load divergence over 8.0 hours mean 934.69 W, min 0.0 W, max 4800.0 W, std dev 609.31 W, divergence 32.59%
2024-06-24 23:30:16.300679 INFO pred_bat: Yesterday basic charge window best: [{'start': 420, 'end': 450, 'average': 12.77}] charge limit best: [10.44]
2024-06-24 23:30:16.512933 INFO pred_bat: predict yesterday end_record 06-25 00:00:00 final soc 0.42 kWh metric 310.93 p metric_keep 129.74 min_soc 0.42 @ 06-24 16:05:00 kWh load 30.3 pv 15.8
2024-06-24 23:30:16.516984 INFO pred_bat:          [   00:00,    00:30,    01:00,    01:30,    02:00,    02:30,    03:00,    03:30,    04:00,    04:30,    05:00,    05:30,    06:00,    06:30,    07:00,    07:30,    08:00,    08:30,    09:00,    09:30,    10:00,    10:30,    11:00,    11:30,    12:00,    12:30,    13:00,    13:30,    14:00,    14:30,    15:00,    15:30,    16:00,    16:30,    17:00,    17:30,    18:00,    18:30,    19:00,    19:30,    20:00,    20:30,    21:00,    21:30,    22:00,    22:30,    23:00,    23:30]
2024-06-24 23:30:16.520761 INFO pred_bat:     SOC: [     0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,     0.02,      1.3,     1.41,     1.25,     1.46,     1.62,     1.85,     1.58,     1.31,     1.47,     1.75,     2.56,     2.78,     2.83,     2.84,     2.59,     1.43,     1.07,     0.61,     0.42,     0.42,     0.77,     0.84,     0.46,     0.51,     0.42,     0.42,     0.42,     0.42,     0.42,     0.42,     0.42,     0.42,     0.42]
**2024-06-24 23:30:16.524053 INFO pred_bat:     BAT: [   g<be-,    g<be-,    g<be-,    g<be-,    g<be-,    g<be-,    g<be-,    g<be-,    g<be-,    g<be-,    g<be-,    g<be-,    g<be-,    g<be-,    g<bf+,    g~be+,    g~be-,    g~be+,    g~be+,    g~be+,    g~be-,    g~be-,    g~be+,    g~be+,    g~be+,    g~be+,    g~be-,    g~be+,    g~be-,    g<be-,    g~be-,    g~be-,    g~be-,    g<be-,    g~be+,    g~be+,    g~be-,    g~be~,    g~be+,    g<be-,    g<be-,    g<be-,    g<be-,    g<be-,    g<be-,    g<be-,    g<be-,    g<be-]**
2024-06-24 23:30:16.527474 INFO pred_bat:    LOAD: [       0,     0.58,     1.07,     1.55,     2.05,      2.6,      3.1,     3.47,     3.96,     4.56,     4.97,     5.39,     5.69,     6.12,      6.6,      7.1,      7.4,      7.9,      8.2,      8.6,     8.98,      9.9,    10.85,    11.55,    12.32,    12.76,    13.14,    13.56,    13.94,     14.7,    16.75,    17.57,    18.43,     20.8,    22.32,     22.8,    23.34,     24.0,    24.68,    25.32,    25.96,    26.62,    27.18,    27.71,    28.22,    28.75,    29.27,    29.83]
2024-06-24 23:30:16.531662 INFO pred_bat:      PV: [       0,     0.01,     0.02,     0.02,     0.03,     0.04,     0.05,     0.06,     0.07,     0.07,     0.08,     0.09,      0.1,     0.25,     0.43,     0.67,      1.1,     1.48,      2.0,     2.58,     3.22,     3.85,     4.58,     5.48,     6.58,      7.9,     8.53,     9.02,     9.43,     9.93,    10.53,    11.03,    11.48,    11.89,     12.2,    13.07,    13.71,    14.03,    14.78,    15.29,    15.49,    15.69,     15.8,     15.8,     15.8,     15.8,     15.8,     15.8]
2024-06-24 23:30:16.535320 INFO pred_bat:  IMPORT: [       0,     0.58,     1.06,     1.53,     2.02,     2.56,     3.05,     3.42,     3.89,     4.49,      4.9,      5.3,      5.6,     5.88,     6.21,     7.83,     7.83,     7.83,     7.83,     7.83,     7.83,      7.9,      7.9,      7.9,      7.9,      7.9,      7.9,      7.9,      7.9,     7.95,     8.34,     8.34,     8.34,    10.14,    11.36,    11.36,    11.36,    11.36,    11.36,    11.44,    11.89,    12.35,    12.81,    13.34,    13.85,    14.38,     14.9,    15.46]
2024-06-24 23:30:16.539138 INFO pred_bat:  EXPORT: [       0,        0,        0,        0,        0,        0,        0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,     0.03,     0.03,     0.03,     0.03,     0.03,     0.03,     0.03,     0.03,     0.03,     0.03,     0.03,     0.03,     0.03,     0.03,     0.03,     0.03,     0.03,     0.03,     0.03,     0.03,     0.03,     0.03,     0.03]
2024-06-24 23:30:16.549114 INFO pred_bat:  METRIC: [       0,     8.89,     16.3,     24.1,     32.2,    40.98,    48.14,    53.63,    61.03,    70.85,    77.12,    83.47,    88.29,    92.44,    97.15,   117.83,   117.83,   117.83,   117.83,   117.83,   117.83,   118.91,   118.91,   118.91,   118.91,   118.91,   118.91,   118.91,   118.91,   119.77,    126.3,    126.3,    126.3,   182.82,   220.36,   220.36,   220.36,   220.36,   220.36,   222.02,   230.76,   241.01,   250.96,   262.57,    273.1,   283.81,   292.21,    302.2]
2024-06-24 23:30:16.551984 INFO pred_bat: Yesterday: Predbat disabled was 352.94p vs real 313.0p saving 39.94p with import 15.93 export 0.03 battery_cycle 9.14 start_soc 0.0 final_soc 0.42
2024-06-24 23:30:16.628317 INFO pred_bat: Yesterday: No Battery/PV system cost predicted was 652.06p vs real 313.0p saving 339.06p with import 30.3 export 0.0
2024-06-24 23:30:16.701918 INFO pred_bat: Calculate Best options: mode(Control charge & discharge) calculate_discharge_oncharge(True) set_discharge_freeze_only(False) set_discharge_during_charge(True) combine_charge_slots(False) combine_discharge_slots(False) combine_rate_threshold(0.0) best_soc_min(0.0 kWh) best_soc_max(0.0 kWh) best_soc_keep(0.5 kWh) inverter_loss(4 %) battery_loss(3 %) battery_loss_discharge (3 %) inverter_hybrid(True) metric_min_improvement(0.0 p) metric_min_improvement_discharge(0.1 p) metric_battery_cycle(0.5 p/kWh) metric_battery_value_scaling(1.0 x) 
2024-06-24 23:30:16.703933 INFO pred_bat: Error: Exception raised unsupported operand type(s) for +=: 'float' and 'NoneType'
2024-06-24 23:30:16.708568 INFO pred_bat: Error: Traceback (most recent call last):
  File "/config/apps/predbat.py", line 11053, in run_time_loop
    self.update_pred(scheduled=True)
  File "/config/apps/predbat.py", line 9891, in update_pred
    recompute = self.calculate_plan(recompute=recompute)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/apps/predbat.py", line 8155, in calculate_plan
    self.optimise_all_windows(metric, metric_keep)
  File "/config/apps/predbat.py", line 6796, in optimise_all_windows
    window_sorted, window_index, price_set, price_links = self.sort_window_by_price_combined(
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/apps/predbat.py", line 6383, in sort_window_by_price_combined
    average += self.metric_self_sufficiency
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'

2024-06-24 23:30:16.942438 INFO pred_bat: Info: record_status Error: Exception raised unsupported operand type(s) for +=: 'float' and 'NoneType'


From what I can see, it looks like  "INFO pred_bat:     BAT:" is reporting random "g<be-,    g<be-,    g<be-,    g<be-" text rather than numbers?  Is that' what's causing the exception?

**Comment by gcoan** [comment]
I had this when I upgraded from v8.0.0 to 8.1.1.  Reverting back and the error stopped.

Tried again to upgrade, same error.  Then I restarted AppDaemon and the error cleared.

Try restarting your appdaemon-predbat add-on

**Comment by TheSargey** [comment]
Simple as that, it fixed it.

I'll have to remember to give appdaemon-predbat a nudge first before flooding the forum!  

Thanks as always sir, much appreciated.
