### ISSUE TITLE
PredBat exception: Failure to fetch history for predbat.status

### ISSUE THREAD

**Issue by adamdoran** [springfall2008/batpred#1319]
**Describe the bug**
Hi Trefor and team. I'm experiencing fairly frequent exceptions, which hang the execution of PredBat lately (after running stable for months). The full details are below, but it appears to happen when PredBat queries HA for history. Restarting the appdaemon container always fixes the issue, but I'm not sure whether this is really a PredBat issue, or something more fundamental with HA. Thank you in advance.

**Expected behavior**
Potentially for this exception to be handled, with graceful retry logic.

**Predbat version**

v8.3.0

**Environment details**

- Inverter and battery setup: GivEnergy HY5.0 Gen3, plus pair of 8.2kWh batteries
- Standard HAOS installer or Docker: Kubernetes cluster comprised of three Raspberry PI 8GB nodes, with appdaemon running in a dedicated namespace/pod, communicating with HA through Cilium CNI, with LetEncrypt TLS cert.
- Anything else?

**Screenshots**
If applicable, add screenshots to help explain your problem. The most useful ones can be your battery chart, the Predbat HTML plan and your current settings in HA.

![predbat-exception](https://github.com/user-attachments/assets/42def728-72e3-43cb-83ca-927d130d4557)

**Log file**

2024-07-19 08:21:01.716196 INFO pred_bat: Refreshing Predbat configuration
2024-07-19 08:21:11.745588 WARNING pred_bat: Coroutine (<coroutine object Hass.get_history at 0xffffa4fc1a10>) took too long (10 seconds), cancelling the task...
2024-07-19 08:21:11.756780 INFO pred_bat: Error: Failure to fetch history for predbat.status
2024-07-19 08:21:11.768866 INFO pred_bat: Error: Exception raised
2024-07-19 08:21:11.782923 INFO pred_bat: Error: Traceback (most recent call last):
  File "/conf/apps/predbat/predbat.py", line 10823, in initialize
    self.load_user_config(quiet=False, register=True)
  File "/conf/apps/predbat/predbat.py", line 10519, in load_user_config
    current_status = self.load_previous_value_from_ha(self.prefix + ".status")
  File "/conf/apps/predbat/predbat.py", line 10457, in load_previous_value_from_ha
    history = self.get_history_wrapper(entity_id=entity)
  File "/conf/apps/predbat/predbat.py", line 948, in get_history_wrapper
    raise ValueError
ValueError

2024-07-19 08:21:11.789909 WARNING pred_bat: pred_bat: Entity predbat.status not found in namespace default
2024-07-19 08:21:11.795623 INFO AppDaemon: pred_bat: Entity predbat.status created in namespace: default
2024-07-19 08:21:12.813881 INFO pred_bat: Info: record_status Error: Exception raised
2024-07-19 08:21:12.820361 WARNING pred_bat: ------------------------------------------------------------
2024-07-19 08:21:12.824700 WARNING pred_bat: Unexpected error running initialize() for pred_bat
2024-07-19 08:21:12.826876 WARNING pred_bat: ------------------------------------------------------------
2024-07-19 08:21:12.834125 WARNING pred_bat: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/appdaemon/app_management.py", line 162, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/local/lib/python3.10/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/conf/apps/predbat/predbat.py", line 10828, in initialize
    raise e
  File "/conf/apps/predbat/predbat.py", line 10823, in initialize
    self.load_user_config(quiet=False, register=True)
  File "/conf/apps/predbat/predbat.py", line 10519, in load_user_config
    current_status = self.load_previous_value_from_ha(self.prefix + ".status")
  File "/conf/apps/predbat/predbat.py", line 10457, in load_previous_value_from_ha
    history = self.get_history_wrapper(entity_id=entity)
  File "/conf/apps/predbat/predbat.py", line 948, in get_history_wrapper
    raise ValueError
ValueError

2024-07-19 08:21:12.836388 WARNING pred_bat: ------------------------------------------------------------

**Comment by adamdoran** [comment]
I'm fairly certain this was an issue with the Home Assistant instance becoming unavailable, and seems to have not occurred since upgrading to HA 2024.8, so closing this issue.
