### ISSUE TITLE
SolaX: TypeError: strptime() argument 1 must be str, not dict

### ISSUE THREAD

**Issue by M0LTE** [springfall2008/batpred#1742]
**Describe the bug**

Solax inverter:

```
predbat  | 2024-12-15 22:30:34.808234: Info: record_status Error: Exception raised strptime() argument 1 must be str, not dict
predbat  | 2024-12-15 22:30:34.808415: Error: strptime() argument 1 must be str, not dict
predbat  | Traceback (most recent call last):
predbat  |   File "/config/hass.py", line 173, in timer_tick
predbat  |     item["callback"](None)
predbat  |   File "/config/predbat.py", line 970, in run_time_loop
predbat  |     raise e
predbat  |   File "/config/predbat.py", line 965, in run_time_loop
predbat  |     self.update_pred(scheduled=True)
predbat  |   File "/config/predbat.py", line 556, in update_pred
predbat  |     status, status_extra = self.execute_plan()
predbat  |                            ^^^^^^^^^^^^^^^^^^^
predbat  |   File "/config/execute.py", line 186, in execute_plan
predbat  |     inverter.adjust_charge_window(charge_start_time, charge_end_time, self.minutes_now)
predbat  |   File "/config/inverter.py", line 2097, in adjust_charge_window
predbat  |     self.press_and_poll_button(entity_id)
predbat  |   File "/config/inverter.py", line 2131, in press_and_poll_button
predbat  |     time_pressed = datetime.strptime(self.base.get_state_wrapper(entity_id, refresh=True), TIME_FORMAT_SECONDS)
predbat  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
predbat  | TypeError: strptime() argument 1 must be str, not dict
```

This appears to be inside this:
```
    def press_and_poll_button(self, entity_id):
        """
        Call a button press service (Solis) and wait for the data to update
        """
```

implying the code should not even be called for SolaX inverters.

**Expected behaviour**

Exception not to happen

**Predbat version**

8.8.9

**Environment details**

- Solax x1 hybrid + master battery + 2x slave battery
- Bottlecap dave modbus
- Docker

**Comment by springfall2008** [comment]
What is in your apps.yaml for 'charge_discharge_update_button' ?

**Comment by springfall2008** [comment]
You should probably turn off the time_button_press inverter option, but I'll change the code to ignore it if commented out

**Comment by springfall2008** [comment]
Fix on main to catch this crash

**Comment by M0LTE** [comment]
@springfall2008 I pulled the updated inverter.py:

```
predbat  | 2024-12-21 16:42:54.009266: Error: Exception raised Inverter.press_and_poll_button() missing 1 required positional argument: 'entity_id'
predbat  | 2024-12-21 16:42:54.016187: Error: Traceback (most recent call last):
predbat  |   File "/config/predbat.py", line 911, in update_time_loop
predbat  |     self.update_pred(scheduled=False)
predbat  |   File "/config/predbat.py", line 556, in update_pred
predbat  |     status, status_extra = self.execute_plan()
predbat  |                            ^^^^^^^^^^^^^^^^^^^
predbat  |   File "/config/execute.py", line 287, in execute_plan
predbat  |     inverter.adjust_force_export(True, discharge_start_time, discharge_end_time)
predbat  |   File "/config/inverter.py", line 1735, in adjust_force_export
predbat  |     self.press_and_poll_button()
predbat  | TypeError: Inverter.press_and_poll_button() missing 1 required positional argument: 'entity_id'
predbat  |
predbat  | 2024-12-21 16:42:54.035835: Info: record_status Error: Exception raised Inverter.press_and_poll_button() missing 1 required positional argument: 'entity_id'
predbat  | 2024-12-21 16:42:54.036026: Error: Inverter.press_and_poll_button() missing 1 required positional argument: 'entity_id'
predbat  | Traceback (most recent call last):
predbat  |   File "/config/hass.py", line 173, in timer_tick
predbat  |     item["callback"](None)
predbat  |   File "/config/predbat.py", line 917, in update_time_loop
predbat  |     raise e
predbat  |   File "/config/predbat.py", line 911, in update_time_loop
predbat  |     self.update_pred(scheduled=False)
predbat  |   File "/config/predbat.py", line 556, in update_pred
predbat  |     status, status_extra = self.execute_plan()
predbat  |                            ^^^^^^^^^^^^^^^^^^^
predbat  |   File "/config/execute.py", line 287, in execute_plan
predbat  |     inverter.adjust_force_export(True, discharge_start_time, discharge_end_time)
predbat  |   File "/config/inverter.py", line 1735, in adjust_force_export
predbat  |     self.press_and_poll_button()
predbat  | TypeError: Inverter.press_and_poll_button() missing 1 required positional argument: 'entity_id'
```

**Comment by M0LTE** [comment]
I think line 2122 just wants changing to `def press_and_poll_button(self):`

**Comment by M0LTE** [comment]
I have now added `time_button_press: False` to my `apps.yml`- it was previously not defined

**Comment by philicibine** [comment]
> charge_discharge_update_button

I am seeing this same error.  I am running a solis inverter with the solax modbus integration.  I guess as its solis.. i do need this button?  Any idea how i can fix?

**Comment by M0LTE** [comment]
I think the fix for the SolaX issue has introduced a bug which might affect
all

**Comment by philicibine** [comment]
Have tried rolling back the version but still seeing this error

```
Error: Inverter.press_and_poll_button() missing 1 required positional argument: 'entity_id'
```

**Comment by springfall2008** [comment]
Fixed on main now
