### ISSUE TITLE
Low priority: Retry on REST call or other fallback?

### ISSUE THREAD

**Issue by gcoan** [springfall2008/batpred#330]
Generally predbat and GivTCP appear to be pretty resilient even when comms issues occur, but have seen twice today failures in the GivTCP log that have caused predbat to go into error state:

```
2023-11-14 12:00:42,550 - Inv2 - sync        -  [ERROR   ] - Connection to (192.168.1.159, 8899) failed: timed out
2023-11-14 12:00:42,550 - Inv2 - write       -  [INFO    ] - Setting Charge Slot 1 failed: (<class 'AssertionError'>, AssertionError('Unexpected response from remote end: Modbus Error: [Connection] Failed to connect[ModbusTcpClient(192.168.1.159:8899)]'), <traceback object at 0x7f1d8ad40d40>)
2023-11-14 12:00:44,896 - Inv2 - sync        -  [ERROR   ] - Connection to (192.168.1.159, 8899) failed: timed out
2023-11-14 12:00:47,459 - Inv2 - sync        -  [ERROR   ] - Connection to (192.168.1.159, 8899) failed: timed out
2023-11-14 12:00:49,965 - Inv2 - sync        -  [ERROR   ] - Connection to (192.168.1.159, 8899) failed: timed out
2023-11-14 12:00:52,476 - Inv2 - sync        -  [ERROR   ] - Connection to (192.168.1.159, 8899) failed: timed out
[2023-11-14 12:00:57 +0000] [64] [CRITICAL] WORKER TIMEOUT (pid:76)
[2023-11-14 12:00:58 +0000] [64] [ERROR] Worker (pid:76) was sent SIGKILL! Perhaps out of memory?
[2023-11-14 12:00:58 +0000] [68783] [INFO] Booting worker with pid: 68783
2023-11-14 12:01:11,611 - Inv2 - write       -  [INFO    ] - Setting Charge Slot 1 to: 11:30 - 16:00
2023-11-14 12:01:29,322 - Inv2 - write       -  [INFO    ] - Setting Charge Slot 1 failed: (<class 'AssertionError'>, AssertionError('Unexpected response from remote end: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] No response received, expected at least 44 bytes (0 received)'), <traceback object at 0x7f1d8ad40ec0>)
[2023-11-14 12:01:41 +0000] [64] [CRITICAL] WORKER TIMEOUT (pid:73)
[2023-11-14 12:01:42 +0000] [64] [ERROR] Worker (pid:73) was sent SIGKILL! Perhaps out of memory?
[2023-11-14 12:01:42 +0000] [68799] [INFO] Booting worker with pid: 68799
```

predbat log:
```
2023-11-14 12:00:06.785897 INFO pred_bat: Include original charge start 11-14 11:30:00, keeping this instead of new start 11-14 11:30:00
2023-11-14 12:00:06.786883 INFO pred_bat: Charge window will be: 2023-11-14 11:30:00+00:00 - 2023-11-14 16:00:00+00:00 - current soc 96.target 4
2023-11-14 12:00:06.788131 INFO pred_bat: Configuring charge window now (now 11-14 11:55:00 target set_window_minutes 30 charge start time 11-14 11:30:00
2023-11-14 12:00:06.789486 INFO pred_bat: Set window new start 690 end 960
2023-11-14 12:00:58.094537 INFO pred_bat: ERROR: Exception raised ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2023-11-14 12:00:58.096455 INFO pred_bat: WARN: Inverter 1 unable to read REST data from http://homeassistant.local:6346/runAll - REST will be disabled
2023-11-14 12:00:58.127466 INFO pred_bat: ERROR: Exception raised 'NoneType' object is not subscriptable
2023-11-14 12:00:58.160783 WARNING AppDaemon: Excessive time spent in callback 'update_time_loop() in pred_bat', Thread 'thread.thread-2' - now complete after 142.159088 seconds (limit=120.0)
2023-11-14 12:00:58.174724 INFO pred_bat: BALANCE: Enabled balance charge False discharge False crosscharge True threshold charge 1.0 discharge 1.0
2023-11-14 12:00:59.443314 INFO pred_bat: Reserve min: 4.0% Battery_min:4.0%
2023-11-14 12:01:00.502885 INFO pred_bat: WARN: Out of range index 1 within item battery_min_soc value 4.0
2023-11-14 12:01:01.626308 INFO pred_bat: Previous message repeated 1 times
2023-11-14 12:01:01.626620 INFO pred_bat: WARN: Out of range index 1 within item inverter_limit_charge value 2600
2023-11-14 12:01:01.628221 INFO pred_bat: WARN: Out of range index 1 within item inverter_limit_discharge value 2600
2023-11-14 12:01:01.630476 INFO pred_bat: WARN: Out of range index 1 within item inverter_battery_rate_min value 0
2023-11-14 12:01:01.632633 INFO pred_bat: WARN: Out of range index 1 within item battery_min_soc value 4.0
2023-11-14 12:01:01.635061 INFO pred_bat: Reserve min: 4.0% Battery_min:4.0%
2023-11-14 12:01:02.762210 INFO pred_bat: WARN: Out of range index 1 within item battery_voltage value 52.0
2023-11-14 12:01:02.763979 INFO pred_bat: BALANCE: socs [98, 96] reserves [0.38, 0.21] battery_powers [6.0, 8.0] total 14.0 battery_max_rates [2600.0, 2600.0] charge_rates [2600.0, 2600.0] pv_power [144.0, 87.0] load_power [83.0, 1397.0] total 5200.0 discharge_rates [0.0, 0.0] total 0.0
2023-11-14 12:01:02.766533 INFO pred_bat: BALANCE: out_of_balance True above_reserve [True, True] below_full [True, True] can_power_house [False, False] can_store_pv [True, True] power_enough_discharge [False, False] power_enough_charge [False, False] soc_low [False, True] soc_high [True, False]
2023-11-14 12:01:02.768961 INFO pred_bat: BALANCE: Completed this run
```

And at 15:10, in the GivTCP log:

```
2023-11-14 15:10:04,314 - Inv1 - app         -  [ERROR   ] - Exception on /readData [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/GivTCP_1/REST.py", line 51, in rdData
    return rd.pubFromPickle()
  File "/app/GivTCP_1/read.py", line 768, in pubFromPickle
    regCacheStack = pickle.load(inp)
EOFError: Ran out of input
```

Caused predbat to go into exception error state, but it still looped round the balance inverters cycle:
```
2023-11-14 15:10:03.142880 INFO pred_bat: Inverter 0 using Rest API http://homeassistant.local:6345
2023-11-14 15:10:04.294005 INFO pred_bat: Invertor time 2023-11-14 15:09:27+00:00 AppDaemon time 2023-11-14 15:10:00.060057+00:00 difference -0.57 minutes
2023-11-14 15:10:04.298850 INFO pred_bat: Reserve min: 4.0% Battery_min:4.0%
2023-11-14 15:10:04.308339 INFO pred_bat: New Inverter 0 with soc_max 9.52 kWh nominal_capacity 9.52 kWh battery rate raw 2600.0 w charge rate 2.6 kw discharge rate 2.6 kw battery_rate_min 0.0 w ac limit 5.0 kw export limit 5.0 kw reserve 4.0 % current_reserve 4.0 %
2023-11-14 15:10:04.337391 INFO pred_bat: WARN: Inverter 0 unable to read REST data from http://homeassistant.local:6345/readData - REST will be disabled
2023-11-14 15:10:04.359060 INFO pred_bat: Inverter 0 SOC: 0.0 kw 0 % Current charge rate 2600.0 w Current discharge rate 2600.0 w Current power 0.0 w Current voltage52.0
2023-11-14 15:10:04.360606 INFO pred_bat: WARN: Inverter 0 unable to read charge window time as neither REST, charge_start_time or charge_start_hour are set
2023-11-14 15:10:04.361576 INFO pred_bat: ERROR: Exception raised cannot access local variable 'charge_start_time' where it is not associated with a value
2023-11-14 15:10:15.083187 INFO pred_bat: BALANCE: Enabled balance charge False discharge False crosscharge True threshold charge 1.0 discharge 1.0
2023-11-14 15:10:16.389979 INFO pred_bat: Reserve min: 4.0% Battery_min:4.0%
2023-11-14 15:10:17.550005 INFO pred_bat: WARN: Out of range index 1 within item battery_min_soc value 4.0
2023-11-14 15:10:18.850980 INFO pred_bat: Previous message repeated 1 times
2023-11-14 15:10:18.851290 INFO pred_bat: WARN: Out of range index 1 within item inverter_limit_charge value 2600
2023-11-14 15:10:18.853250 INFO pred_bat: WARN: Out of range index 1 within item inverter_limit_discharge value 2600
2023-11-14 15:10:18.859319 INFO pred_bat: WARN: Out of range index 1 within item inverter_battery_rate_min value 0
2023-11-14 15:10:18.861514 INFO pred_bat: WARN: Out of range index 1 within item battery_min_soc value 4.0
2023-11-14 15:10:18.864224 INFO pred_bat: Reserve min: 4.0% Battery_min:4.0%
2023-11-14 15:10:19.943882 INFO pred_bat: WARN: Out of range index 1 within item battery_voltage value 52.0
2023-11-14 15:10:19.945077 INFO pred_bat: BALANCE: socs [98, 98] reserves [0.38, 0.21] battery_powers [4.0, 5.0] total 9.0 battery_max_rates [2600.0, 2600.0] charge_rates [2600.0, 2600.0] pv_power [163.0, 447.0] load_power [2298.0, 2545.0] total 5200.0 discharge_rates [0.0, 0.0] total 0.0
2023-11-14 15:10:19.946499 INFO pred_bat: BALANCE: out_of_balance False above_reserve [True, True] below_full [True, True] can_power_house [False, False] can_store_pv [True, True] power_enough_discharge [False, False] power_enough_charge [False, False] soc_low [False, False] soc_high [False, False]
2023-11-14 15:10:19.948303 INFO pred_bat: BALANCE: Completed this run
2023-11-14 15:11:15.049597 INFO pred_bat: BALANCE: Enabled balance charge False discharge False crosscharge True threshold charge 1.0 discharge 1.0
2023-11-14 15:11:16.156111 INFO pred_bat: Reserve min: 4.0% Battery_min:4.0%
2023-11-14 15:11:17.303261 INFO pred_bat: WARN: Out of range index 1 within item battery_min_soc value 4.0
2023-11-14 15:11:18.381133 INFO pred_bat: Previous message repeated 1 times
2023-11-14 15:11:18.381402 INFO pred_bat: WARN: Out of range index 1 within item inverter_limit_charge value 2600
2023-11-14 15:11:18.383236 INFO pred_bat: WARN: Out of range index 1 within item inverter_limit_discharge value 2600
2023-11-14 15:11:18.386283 INFO pred_bat: WARN: Out of range index 1 within item inverter_battery_rate_min value 0
2023-11-14 15:11:18.388627 INFO pred_bat: WARN: Out of range index 1 within item battery_min_soc value 4.0
2023-11-14 15:11:18.390409 INFO pred_bat: Reserve min: 4.0% Battery_min:4.0%
2023-11-14 15:11:19.665004 INFO pred_bat: WARN: Out of range index 1 within item battery_voltage value 52.0
2023-11-14 15:11:19.670913 INFO pred_bat: BALANCE: socs [98, 98] reserves [0.38, 0.21] battery_powers [5.0, 5.0] total 10.0 battery_max_rates [2600.0, 2600.0] charge_rates [2600.0, 2600.0] pv_power [157.0, 459.0] load_power [2304.0, 2561.0] total 5200.0 discharge_rates [0.0, 0.0] total 0.0
2023-11-14 15:11:19.674814 INFO pred_bat: BALANCE: out_of_balance False above_reserve [True, True] below_full [True, True] can_power_house [False, False] can_store_pv [True, True] power_enough_discharge [False, False] power_enough_charge [False, False] soc_low [False, False] soc_high [False, False]
2023-11-14 15:11:19.677483 INFO pred_bat: BALANCE: Completed this run
2023-11-14 15:12:15.042419 INFO pred_bat: BALANCE: Enabled balance charge False discharge False crosscharge True threshold charge 1.0 discharge 1.0
2023-11-14 15:12:16.295531 INFO pred_bat: Reserve min: 4.0% Battery_min:4.0%
2023-11-14 15:12:17.385435 INFO pred_bat: WARN: Out of range index 1 within item battery_min_soc value 4.0
2023-11-14 15:12:18.457459 INFO pred_bat: Previous message repeated 1 times
2023-11-14 15:12:18.458042 INFO pred_bat: WARN: Out of range index 1 within item inverter_limit_charge value 2600
2023-11-14 15:12:18.460237 INFO pred_bat: WARN: Out of range index 1 within item inverter_limit_discharge value 2600
2023-11-14 15:12:18.461558 INFO pred_bat: WARN: Out of range index 1 within item inverter_battery_rate_min value 0
2023-11-14 15:12:18.463378 INFO pred_bat: WARN: Out of range index 1 within item battery_min_soc value 4.0
2023-11-14 15:12:18.464577 INFO pred_bat: Reserve min: 4.0% Battery_min:4.0%
2023-11-14 15:12:19.540838 INFO pred_bat: WARN: Out of range index 1 within item battery_voltage value 52.0
2023-11-14 15:12:19.542647 INFO pred_bat: BALANCE: socs [98, 98] reserves [0.38, 0.21] battery_powers [4.0, 6.0] total 10.0 battery_max_rates [2600.0, 2600.0] charge_rates [2600.0, 2600.0] pv_power [145.0, 379.0] load_power [1010.0, 1209.0] total 5200.0 discharge_rates [0.0, 0.0] total 0.0
2023-11-14 15:12:19.544560 INFO pred_bat: BALANCE: out_of_balance False above_reserve [True, True] below_full [True, True] can_power_house [False, False] can_store_pv [True, True] power_enough_discharge [False, False] power_enough_charge [False, False] soc_low [False, False] soc_high [False, False]
2023-11-14 15:12:19.546032 INFO pred_bat: BALANCE: Completed this run
2023-11-14 15:13:15.019980 INFO pred_bat: BALANCE: Enabled balance charge False discharge False crosscharge True threshold charge 1.0 discharge 1.0
2023-11-14 15:13:16.271879 INFO pred_bat: Reserve min: 4.0% Battery_min:4.0%
2023-11-14 15:13:17.457238 INFO pred_bat: WARN: Out of range index 1 within item battery_min_soc value 4.0
2023-11-14 15:13:18.544292 INFO pred_bat: Previous message repeated 1 times
2023-11-14 15:13:18.544475 INFO pred_bat: WARN: Out of range index 1 within item inverter_limit_charge value 2600
2023-11-14 15:13:18.548236 INFO pred_bat: WARN: Out of range index 1 within item inverter_limit_discharge value 2600
2023-11-14 15:13:18.555036 INFO pred_bat: WARN: Out of range index 1 within item inverter_battery_rate_min value 0
2023-11-14 15:13:18.557481 INFO pred_bat: WARN: Out of range index 1 within item battery_min_soc value 4.0
2023-11-14 15:13:18.560085 INFO pred_bat: Reserve min: 4.0% Battery_min:4.0%
2023-11-14 15:13:19.625626 INFO pred_bat: WARN: Out of range index 1 within item battery_voltage value 52.0
2023-11-14 15:13:19.627439 INFO pred_bat: BALANCE: socs [98, 98] reserves [0.38, 0.21] battery_powers [5.0, -361.0] total -356.0 battery_max_rates [2600.0, 2600.0] charge_rates [2600.0, 2600.0] pv_power [136.0, 352.0] load_power [66.0, 0.0] total 5200.0 discharge_rates [0.0, 0.0] total 0.0
2023-11-14 15:13:19.629496 INFO pred_bat: BALANCE: out_of_balance False above_reserve [True, True] below_full [True, True] can_power_house [True, True] can_store_pv [True, True] power_enough_discharge [False, False] power_enough_charge [False, True] soc_low [False, False] soc_high [False, False]
2023-11-14 15:13:19.631032 INFO pred_bat: BALANCE: Completed this run
2023-11-14 15:14:15.018213 INFO pred_bat: BALANCE: Enabled balance charge False discharge False crosscharge True threshold charge 1.0 discharge 1.0
2023-11-14 15:14:16.275954 INFO pred_bat: Reserve min: 4.0% Battery_min:4.0%
2023-11-14 15:14:17.336262 INFO pred_bat: WARN: Out of range index 1 within item battery_min_soc value 4.0
2023-11-14 15:14:18.450515 INFO pred_bat: Previous message repeated 1 times
2023-11-14 15:14:18.451063 INFO pred_bat: WARN: Out of range index 1 within item inverter_limit_charge value 2600
2023-11-14 15:14:18.453511 INFO pred_bat: WARN: Out of range index 1 within item inverter_limit_discharge value 2600
2023-11-14 15:14:18.455255 INFO pred_bat: WARN: Out of range index 1 within item inverter_battery_rate_min value 0
2023-11-14 15:14:18.457343 INFO pred_bat: WARN: Out of range index 1 within item battery_min_soc value 4.0
2023-11-14 15:14:18.459417 INFO pred_bat: Reserve min: 4.0% Battery_min:4.0%
2023-11-14 15:14:19.547953 INFO pred_bat: WARN: Out of range index 1 within item battery_voltage value 52.0
2023-11-14 15:14:19.549646 INFO pred_bat: BALANCE: socs [98, 98] reserves [0.38, 0.21] battery_powers [5.0, -340.0] total -335.0 battery_max_rates [2600.0, 2600.0] charge_rates [2600.0, 2600.0] pv_power [131.0, 336.0] load_power [17.0, 0.0] total 5200.0 discharge_rates [0.0, 0.0] total 0.0
2023-11-14 15:14:19.553315 INFO pred_bat: BALANCE: out_of_balance False above_reserve [True, True] below_full [True, True] can_power_house [True, True] can_store_pv [True, True] power_enough_discharge [False, False] power_enough_charge [False, True] soc_low [False, False] soc_high [False, False]
2023-11-14 15:14:19.554763 INFO pred_bat: BALANCE: Completed this run
```

In both cases predbat went into an exception error state, but the very next 5 minute run, it all worked OK.  Is there any more retries or fallback logic that can be added to predbat to prevent this exception error?
![image](https://github.com/springfall2008/batpred/assets/142018870/1f793b96-f60a-4a90-8a97-543d8719d600)

Also, noticed that seem to be getting more 'out of range warnings' in the log files, particularly in the balance inverters run.  Iterating beyond the end of an array?
```
2023-11-14 19:33:15.014120 INFO pred_bat: BALANCE: Enabled balance charge False discharge False crosscharge True threshold charge 1.0 discharge 1.0
2023-11-14 19:33:17.153345 INFO pred_bat: Reserve min: 4.0% Battery_min:4.0%
2023-11-14 19:33:18.311791 INFO pred_bat: WARN: Out of range index 1 within item battery_min_soc value 4.0
2023-11-14 19:33:19.435602 INFO pred_bat: Previous message repeated 1 times
2023-11-14 19:33:19.436418 INFO pred_bat: WARN: Out of range index 1 within item inverter_limit_charge value 2600
2023-11-14 19:33:19.440550 INFO pred_bat: WARN: Out of range index 1 within item inverter_limit_discharge value 2600
2023-11-14 19:33:19.447078 INFO pred_bat: WARN: Out of range index 1 within item inverter_battery_rate_min value 0
2023-11-14 19:33:19.457537 INFO pred_bat: WARN: Out of range index 1 within item battery_min_soc value 4.0
2023-11-14 19:33:19.463389 INFO pred_bat: Reserve min: 4.0% Battery_min:4.0%
2023-11-14 19:33:20.538339 INFO pred_bat: WARN: Out of range index 1 within item battery_voltage value 52.0
2023-11-14 19:33:20.540186 INFO pred_bat: BALANCE: socs [44, 18] reserves [4.38, 2.4] battery_powers [-2423.0, -2423.0] total -4846.0 battery_max_rates [2600.0, 2600.0] charge_rates [2600.0, 2600.0] pv_power [0.0, 0.0] load_power [5519.0, 5517.0] total 5200.0 discharge_rates [2600.0, 2600.0] total 5200.0
2023-11-14 19:33:20.541528 INFO pred_bat: BALANCE: out_of_balance True above_reserve [True, True] below_full [True, True] can_power_house [True, True] can_store_pv [True, True] power_enough_discharge [False, False] power_enough_charge [True, True] soc_low [False, True] soc_high [True, False]
2023-11-14 19:33:20.543094 INFO pred_bat: BALANCE: Completed this run
2023-11-14 19:34:15.031333 INFO pred_bat: BALANCE: Enabled balance charge False discharge False crosscharge True threshold charge 1.0 discharge 1.0
2023-11-14 19:34:16.143642 INFO pred_bat: Reserve min: 4.0% Battery_min:4.0%
2023-11-14 19:34:17.361176 INFO pred_bat: WARN: Out of range index 1 within item battery_min_soc value 4.0
2023-11-14 19:34:18.444491 INFO pred_bat: Previous message repeated 1 times
2023-11-14 19:34:18.445077 INFO pred_bat: WARN: Out of range index 1 within item inverter_limit_charge value 2600
2023-11-14 19:34:18.447246 INFO pred_bat: WARN: Out of range index 1 within item inverter_limit_discharge value 2600
2023-11-14 19:34:18.450223 INFO pred_bat: WARN: Out of range index 1 within item inverter_battery_rate_min value 0
2023-11-14 19:34:18.452473 INFO pred_bat: WARN: Out of range index 1 within item battery_min_soc value 4.0
2023-11-14 19:34:18.454152 INFO pred_bat: Reserve min: 4.0% Battery_min:4.0%
2023-11-14 19:34:19.571357 INFO pred_bat: WARN: Out of range index 1 within item battery_voltage value 52.0
```

**Comment by springfall2008** [comment]
Fixed in: https://github.com/springfall2008/batpred/commit/e53f8c7e59368aca97547da1ecff9212a3f6aa90
