### ISSUE TITLE
predbat fails to retrieve octopus rate info

### ISSUE THREAD

**Issue by jws1987** [springfall2008/batpred#379]
predbat fails to retrieve entity for metric_octopus_import even though it's configured correctly.

I believe it's do with the all_rates attribute being removed from the octopus entity:

https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/commit/280e6d25fcb18ce17df158734f9cba3cd7d92574#diff-69d214d99963438893aa86d1d79d95229ff033e87bdff31af4fe66b282d23b77

`2023-11-27 14:25:01.254839 INFO pred_bat: Error: metric_octopus_import is not set correctly or no energy rates can be read
2023-11-27 14:25:01.280301 INFO pred_bat: ERROR: Exception raised 
2023-11-27 14:25:01.305389 WARNING pred_bat: ------------------------------------------------------------
2023-11-27 14:25:01.307394 WARNING pred_bat: Unexpected error in worker for App pred_bat:
2023-11-27 14:25:01.308276 WARNING pred_bat: Worker Ags: {'id': '993138d7963144d288ef3fcbfb556edc', 'name': 'pred_bat', 'objectid': '9d537e2193394f3ba04727e8f8e2d087', 'type': 'scheduler', 'function': <bound method PredBat.run_time_loop of <predbat.PredBat object at 0x7f8569c4d0>>, 'pin_app': True, 'pin_thread': 0, 'kwargs': {'interval': 300, 'random_start': 0, 'random_end': 0, '__thread_id': 'thread-0'}}
2023-11-27 14:25:01.309175 WARNING pred_bat: ------------------------------------------------------------
2023-11-27 14:25:01.312696 WARNING pred_bat: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/threading.py", line 1022, in worker
    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/usr/lib/python3.11/site-packages/appdaemon/adbase.py", line 35, in f_app_lock
    return f(*args, **kw)
           ^^^^^^^^^^^^^^
  File "/config/apps/batpred/predbat.py", line 9244, in run_time_loop
    raise e
  File "/config/apps/batpred/predbat.py", line 9240, in run_time_loop
    self.update_pred(scheduled=True)
  File "/usr/lib/python3.11/site-packages/appdaemon/adbase.py", line 35, in f_app_lock
    return f(*args, **kw)
           ^^^^^^^^^^^^^^
  File "/config/apps/batpred/predbat.py", line 8690, in update_pred
    self.fetch_sensor_data()
  File "/config/apps/batpred/predbat.py", line 8159, in fetch_sensor_data
    raise ValueError
ValueError`

**Comment by jws1987** [comment]
> I had the same issue. My solution was to delete all the octopus energy entities tied to the Octopus Energy integration, delete the integration and set it up fresh. Worked like a charm and no more errors in Predbat so this is definitely not a Predbat issue.

I did try this once, but I've just done it again and everything has sprung into life.  Thanks for the assistance, will close.
